name: prodigy-cryst
channels:
  - defaults
  - conda-forge
dependencies:
  - cython>=0.29.33
  - numpy<1.24
  - biopython=1.79
  - scikit-learn=0.22
  - coverage
  - pytest
  - pytest-cov
  - hypothesis
  - pip:
      - freesasa==2.1.0
