name: unittests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - name: pull anaconda3:2022.10 image
        run: docker pull continuumio/anaconda3:2022.10

      - name: run the container
        run: |
          docker run --name test-anaconda-container -d -v ${{ github.workspace }}:/workspace continuumio/anaconda3:2022.10 tail -f /dev/null

      - name: install system dependencies
        run: |
          docker exec test-anaconda-container apt-get update
          docker exec test-anaconda-container apt-get install -y --no-install-recommends build-essential

      - name: install python dependencies
        run: |
          docker exec test-anaconda-container pip install -r workspace/requirements.txt coverage pytest pytest-cov hypothesis

      - name: run tests
        run: |
          docker exec test-anaconda-container pytest --cov --cov-report=term-missing --cov-append -vv --hypothesis-show-statistics workspace/

      - uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: workspace/coverage.xml
