name: unittests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.9

      # - uses: actions/setup-python@v2.2.2
      #   with:
      #     python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt coverage pytest pytest-cov hypothesis

      - name: Test
        run: |
          pytest --cov --cov-report=term-missing --cov-append -vv --hypothesis-show-statistics .
          coverage xml

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml

      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
